# Config file for automatic testing at travis-ci.org

language: python
dist: bionic
python:
  - "3.11"
  - "3.10"
  - "3.9"
  - "3.8"
  - "3.6"

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install https://github.com/idekerlab/cellmaps_utils/archive/master.zip
    - pip install -r requirements.txt
    - pip install coveralls

# Command to run tests, e.g. python setup.py test
script:
    - coverage run --source cellmaps_generate_ppi -m unittest discover

after_success: coveralls

    
